#!/bin/sh

work_dir=$(pwd)
echo "source $work_dir/MySource/setup.bash">> ~/.bashrc
chmod 777 "$work_dir" -R
rm "$work_dir"/MySource/ros.bash
touch "$work_dir"/MySource/ros.bash
echo "#!/usr/bin/env sh">>"$work_dir"/MySource/ros.bash
