#!/bin/sh

mkdir src
catkin_make
work_dir=$(pwd)
work_name="${work_dir##*/}"
echo "source $work_dir/devel/setup.bash">> ~/.bashrc
echo "export GAZEBO_MODEL_PATH=$work_dir/src/"$work_name"_gazebo/resources/media/models":'${GAZEBO_MODEL_PATH}'>> $work_dir/devel/setup.bash
echo "export GAZEBO_RESOURCE_PATH=$work_dir/src/"$work_name"_gazebo/resources":'${GAZEBO_RESOURCE_PATH}'>> $work_dir/devel/setup.bash
cd src
catkin_create_pkg "$work_name"_gazebo
cd "$work_name"_gazebo
mkdir launch resources
cd resources
mkdir models media worlds
cd media
mkdir materials models
cd materials
mkdir scrips textures programs
