import RPi.GPIO as GPIO

GPIO.setup(2, GPIO.in)
GPIO.setup(3, GPIO.in)
GPIO.setup(4, GPIO.in)
GPIO.setup(17, GPIO.in)
GPIO.setup(27, GPIO.in)
GPIO.setup(27, GPIO.in)
GPIO.setup(27, GPIO.in)
GPIO.setup(27, GPIO.in)
GPIO.setup(27, GPIO.in)
GPIO.setup(27, GPIO.in)
GPIO.setup(27, GPIO.in)
GPIO.setup(27, GPIO.in)
GPIO.setup(27, GPIO.in)
GPIO.setup(27, GPIO.in)
GPIO.setup(27, GPIO.in)
GPIO.setup(27, GPIO.in)
GPIO.setup(27, GPIO.in)
GPIO.setup(27, GPIO.in)
GPIO.cleanup()
