#!/bin/sh

source_dir=$(dirname "$(cd `dirname $0`; pwd)")
command=$1

if [ ! -n "$1" ] ;then
  command="None"
fi
if [ $command = "-c" ];then
  gcc $2 -o ${2%.*}
  ./${2%.*} $3 $4 $5 $6 $7 $8 $9
elif [ $command = "-c++" ];then
  g++ $2 -o ${2%.*} -pthread -std=c++11
  ./${2%.*} $3 $4 $5 $6 $7 $8 $9
elif [ $command = "-opencv" ];then
  g++ $2 -o ${2%.*} `pkg-config opencv --cflags --libs`
  ./${2%.*} $3 $4 $5 $6 $7 $8 $9
elif [ $command = "-systemc" ];then
  g++ $2 -o ${2%.*} -I/home/my/systemc-2.3.3/include/ -L/home/my/systemc-2.3.3/lib-linux64 -lsystemc
  ./${2%.*} $3 $4 $5 $6 $7 $8 $9
else
    echo "-c compile c file and run"
    echo "-c++ compile c++ file and run"
    echo "-opencv compile c++ file with opencv and run"
    echo "-systemc compile c++ file with systemc and run"
fi
