#!/bin/sh

source_dir=$(dirname "$(cd `dirname $0`; pwd)")
command=$1

if [ ! -n "$1" ] ;then
  command="None"
fi
if [ $command = "r" ];then
  echo $ROS_PACKAGE_PATH
elif [ $command = "p" ];then
  echo $PATH
else
    echo "-r to echo ROS_PACKAGE_PATH"
    echo "-p to echo PATH"
fi
